### PR TITLE
Fix LeaderElectionID passed to NewManager.

### LINKED ISSUE #27: Cannot pick BatchTransfer  resources in blueprint namespace to reconcile
I am struggling trying to enable the implicit copy in a multi-cluster environment. By specifying the workload and asset in different cluster with different region, now the read module and copy module got deployed in different cluster and BatchTransfer resource is created. But unfortunately the data-movement-operator dos not pick the resource to reconcile at all.
After some investigation I found my BatchTransfer is created in the fybrik-blueprints namespace as below,
```
apiVersion: v1
items:
- apiVersion: motion.fybrik.io/v1alpha1
  kind: BatchTransfer
  metadata:
....................
    name: my-notebook-fybrik-notebook-sample-implicit-cop-a9308
    namespace: fybrik-blueprints
.....................
  spec:
    destination:
      description: s3://my-notebook-fybrik-notebook-sample12b73371af/Synthetic Financial
        Datasets For Fraud Detection4afecbad70
```
But the data-movement-operator is deployed in fybrik-system namespace and checked there's no appropriate cluster role for manager. 
I think we need create correct RBAC rules for data-movement-operator, especially after we make the module namespace configurable now.

### PR DESCRIPTION
**Pull request by revit13**
This PR fixes LeaderElectionID passed to NewManager.

Closes #27

### CODE REVIEW

File: manager/main.go [hunk 1]
```diff
@@ -71,7 +71,7 @@ func run(namespace string, metricsAddr string, enableLeaderElection bool) int {
 		Namespace:          namespace,
 		MetricsBindAddress: metricsAddr,
 		LeaderElection:     enableLeaderElection,
-		LeaderElectionID:   "fybrik-operator-leader-election",
+		LeaderElectionID:   "data-movement-operator-leader-election-role",
```
Comment (pugangxa) [inline manager/main.go]: data-movement-operator-leader-election?

Comment (revit13) [reply manager/main.go]: Fixed Thanks

**Review by shlomitk1 — APPROVED** [review]
